// File generated from our OpenAPI spec by Stainless.

package ai.llamaindex.llamacloudadmin.models.organizations

import ai.llamaindex.llamacloudadmin.core.jsonMapper
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class OrganizationGetUsageResponseTest {

    @Test
    fun create() {
        val organizationGetUsageResponse =
            OrganizationGetUsageResponse.builder()
                .plan(
                    OrganizationGetUsageResponse.Plan.builder()
                        .limits(
                            OrganizationGetUsageResponse.Plan.Limits.builder()
                                .allowPayAsYouGo(true)
                                .maxConcurrentIndexJobs(0L)
                                .maxConcurrentParseJobsOther(0L)
                                .maxConcurrentParseJobsPremium(0L)
                                .maxDataSinks(0L)
                                .maxDataSources(0L)
                                .maxEmbeddingModels(0L)
                                .maxExtractionAgents(0L)
                                .maxExtractionJobs(0L)
                                .maxExtractionRuns(0L)
                                .maxFilesPerIndex(0L)
                                .maxIndexes(0L)
                                .maxMonthlyInvoiceTotalUsd(0L)
                                .maxOrganizations(0L)
                                .maxPagesPerIndex(0L)
                                .maxProjects(0L)
                                .maxPublishedAgents(0L)
                                .maxReportAgentSessions(0L)
                                .maxUsers(0L)
                                .mfaEnabled(true)
                                .ssoEnabled(true)
                                .subscriptionCostUsd(0L)
                                .maxDirectories(0L)
                                .maxDirectoryFilesPerDirectory(0L)
                                .maxDirectoryIngestFiles(0L)
                                .maxDirectorySyncPlanActions(0L)
                                .addSpendingSoftAlertsUsdCent(0L)
                                .build()
                        )
                        .metronomePlanType(
                            OrganizationGetUsageResponse.Plan.MetronomePlanType.CONTRACT
                        )
                        .metronomeRateCardAlias("metronome_rate_card_alias")
                        .name(OrganizationGetUsageResponse.Plan.Name.ENTERPRISE)
                        .planFrequency(OrganizationGetUsageResponse.Plan.PlanFrequency.ANNUAL)
                        .id("id")
                        .currentBillingPeriod(
                            OrganizationGetUsageResponse.Plan.CurrentBillingPeriod.builder()
                                .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .failureCount(0L)
                        .isPaymentFailed(true)
                        .metronomeCustomerId("metronome_customer_id")
                        .addRecurringCredit(
                            OrganizationGetUsageResponse.Plan.RecurringCredit.builder()
                                .creditAmount(0L)
                                .creditType(
                                    OrganizationGetUsageResponse.Plan.RecurringCredit.CreditType
                                        .builder()
                                        .id("id")
                                        .name("name")
                                        .build()
                                )
                                .name("name")
                                .priority(0.0)
                                .productId("product_id")
                                .rolloverFraction(0.0)
                                .periodsDuration(0.0)
                                .build()
                        )
                        .startingOn(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .usage(
                    OrganizationGetUsageResponse.Usage.builder()
                        .addActiveAlert(
                            OrganizationGetUsageResponse.Usage.ActiveAlert
                                .CONFIGURED_SPEND_LIMIT_EXCEEDED
                        )
                        .addActiveFreeCreditsUsage(
                            OrganizationGetUsageResponse.Usage.ActiveFreeCreditsUsage.builder()
                                .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .grantName("grant_name")
                                .remainingBalance(0L)
                                .startingBalance(0L)
                                .build()
                        )
                        .currentInvoiceTotalUsdCents(0L)
                        .totalExtractionAgents(0L)
                        .totalIndexedPages(0L)
                        .totalIndexes(0L)
                        .totalUsers(0L)
                        .build()
                )
                .build()

        assertThat(organizationGetUsageResponse.plan())
            .isEqualTo(
                OrganizationGetUsageResponse.Plan.builder()
                    .limits(
                        OrganizationGetUsageResponse.Plan.Limits.builder()
                            .allowPayAsYouGo(true)
                            .maxConcurrentIndexJobs(0L)
                            .maxConcurrentParseJobsOther(0L)
                            .maxConcurrentParseJobsPremium(0L)
                            .maxDataSinks(0L)
                            .maxDataSources(0L)
                            .maxEmbeddingModels(0L)
                            .maxExtractionAgents(0L)
                            .maxExtractionJobs(0L)
                            .maxExtractionRuns(0L)
                            .maxFilesPerIndex(0L)
                            .maxIndexes(0L)
                            .maxMonthlyInvoiceTotalUsd(0L)
                            .maxOrganizations(0L)
                            .maxPagesPerIndex(0L)
                            .maxProjects(0L)
                            .maxPublishedAgents(0L)
                            .maxReportAgentSessions(0L)
                            .maxUsers(0L)
                            .mfaEnabled(true)
                            .ssoEnabled(true)
                            .subscriptionCostUsd(0L)
                            .maxDirectories(0L)
                            .maxDirectoryFilesPerDirectory(0L)
                            .maxDirectoryIngestFiles(0L)
                            .maxDirectorySyncPlanActions(0L)
                            .addSpendingSoftAlertsUsdCent(0L)
                            .build()
                    )
                    .metronomePlanType(OrganizationGetUsageResponse.Plan.MetronomePlanType.CONTRACT)
                    .metronomeRateCardAlias("metronome_rate_card_alias")
                    .name(OrganizationGetUsageResponse.Plan.Name.ENTERPRISE)
                    .planFrequency(OrganizationGetUsageResponse.Plan.PlanFrequency.ANNUAL)
                    .id("id")
                    .currentBillingPeriod(
                        OrganizationGetUsageResponse.Plan.CurrentBillingPeriod.builder()
                            .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .failureCount(0L)
                    .isPaymentFailed(true)
                    .metronomeCustomerId("metronome_customer_id")
                    .addRecurringCredit(
                        OrganizationGetUsageResponse.Plan.RecurringCredit.builder()
                            .creditAmount(0L)
                            .creditType(
                                OrganizationGetUsageResponse.Plan.RecurringCredit.CreditType
                                    .builder()
                                    .id("id")
                                    .name("name")
                                    .build()
                            )
                            .name("name")
                            .priority(0.0)
                            .productId("product_id")
                            .rolloverFraction(0.0)
                            .periodsDuration(0.0)
                            .build()
                    )
                    .startingOn(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(organizationGetUsageResponse.usage())
            .isEqualTo(
                OrganizationGetUsageResponse.Usage.builder()
                    .addActiveAlert(
                        OrganizationGetUsageResponse.Usage.ActiveAlert
                            .CONFIGURED_SPEND_LIMIT_EXCEEDED
                    )
                    .addActiveFreeCreditsUsage(
                        OrganizationGetUsageResponse.Usage.ActiveFreeCreditsUsage.builder()
                            .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .grantName("grant_name")
                            .remainingBalance(0L)
                            .startingBalance(0L)
                            .build()
                    )
                    .currentInvoiceTotalUsdCents(0L)
                    .totalExtractionAgents(0L)
                    .totalIndexedPages(0L)
                    .totalIndexes(0L)
                    .totalUsers(0L)
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val organizationGetUsageResponse =
            OrganizationGetUsageResponse.builder()
                .plan(
                    OrganizationGetUsageResponse.Plan.builder()
                        .limits(
                            OrganizationGetUsageResponse.Plan.Limits.builder()
                                .allowPayAsYouGo(true)
                                .maxConcurrentIndexJobs(0L)
                                .maxConcurrentParseJobsOther(0L)
                                .maxConcurrentParseJobsPremium(0L)
                                .maxDataSinks(0L)
                                .maxDataSources(0L)
                                .maxEmbeddingModels(0L)
                                .maxExtractionAgents(0L)
                                .maxExtractionJobs(0L)
                                .maxExtractionRuns(0L)
                                .maxFilesPerIndex(0L)
                                .maxIndexes(0L)
                                .maxMonthlyInvoiceTotalUsd(0L)
                                .maxOrganizations(0L)
                                .maxPagesPerIndex(0L)
                                .maxProjects(0L)
                                .maxPublishedAgents(0L)
                                .maxReportAgentSessions(0L)
                                .maxUsers(0L)
                                .mfaEnabled(true)
                                .ssoEnabled(true)
                                .subscriptionCostUsd(0L)
                                .maxDirectories(0L)
                                .maxDirectoryFilesPerDirectory(0L)
                                .maxDirectoryIngestFiles(0L)
                                .maxDirectorySyncPlanActions(0L)
                                .addSpendingSoftAlertsUsdCent(0L)
                                .build()
                        )
                        .metronomePlanType(
                            OrganizationGetUsageResponse.Plan.MetronomePlanType.CONTRACT
                        )
                        .metronomeRateCardAlias("metronome_rate_card_alias")
                        .name(OrganizationGetUsageResponse.Plan.Name.ENTERPRISE)
                        .planFrequency(OrganizationGetUsageResponse.Plan.PlanFrequency.ANNUAL)
                        .id("id")
                        .currentBillingPeriod(
                            OrganizationGetUsageResponse.Plan.CurrentBillingPeriod.builder()
                                .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .failureCount(0L)
                        .isPaymentFailed(true)
                        .metronomeCustomerId("metronome_customer_id")
                        .addRecurringCredit(
                            OrganizationGetUsageResponse.Plan.RecurringCredit.builder()
                                .creditAmount(0L)
                                .creditType(
                                    OrganizationGetUsageResponse.Plan.RecurringCredit.CreditType
                                        .builder()
                                        .id("id")
                                        .name("name")
                                        .build()
                                )
                                .name("name")
                                .priority(0.0)
                                .productId("product_id")
                                .rolloverFraction(0.0)
                                .periodsDuration(0.0)
                                .build()
                        )
                        .startingOn(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .usage(
                    OrganizationGetUsageResponse.Usage.builder()
                        .addActiveAlert(
                            OrganizationGetUsageResponse.Usage.ActiveAlert
                                .CONFIGURED_SPEND_LIMIT_EXCEEDED
                        )
                        .addActiveFreeCreditsUsage(
                            OrganizationGetUsageResponse.Usage.ActiveFreeCreditsUsage.builder()
                                .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .grantName("grant_name")
                                .remainingBalance(0L)
                                .startingBalance(0L)
                                .build()
                        )
                        .currentInvoiceTotalUsdCents(0L)
                        .totalExtractionAgents(0L)
                        .totalIndexedPages(0L)
                        .totalIndexes(0L)
                        .totalUsers(0L)
                        .build()
                )
                .build()

        val roundtrippedOrganizationGetUsageResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(organizationGetUsageResponse),
                jacksonTypeRef<OrganizationGetUsageResponse>(),
            )

        assertThat(roundtrippedOrganizationGetUsageResponse).isEqualTo(organizationGetUsageResponse)
    }
}
