// File generated from our OpenAPI spec by Stainless.

package ai.llamaindex.llamacloudadmin.models.projects

import ai.llamaindex.llamacloudadmin.core.jsonMapper
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ProjectGetUsageResponseTest {

    @Test
    fun create() {
        val projectGetUsageResponse =
            ProjectGetUsageResponse.builder()
                .plan(
                    ProjectGetUsageResponse.Plan.builder()
                        .limits(
                            ProjectGetUsageResponse.Plan.Limits.builder()
                                .allowPayAsYouGo(true)
                                .maxConcurrentIndexJobs(0L)
                                .maxConcurrentParseJobsOther(0L)
                                .maxConcurrentParseJobsPremium(0L)
                                .maxDataSinks(0L)
                                .maxDataSources(0L)
                                .maxEmbeddingModels(0L)
                                .maxExtractionAgents(0L)
                                .maxExtractionJobs(0L)
                                .maxExtractionRuns(0L)
                                .maxFilesPerIndex(0L)
                                .maxIndexes(0L)
                                .maxMonthlyInvoiceTotalUsd(0L)
                                .maxOrganizations(0L)
                                .maxPagesPerIndex(0L)
                                .maxProjects(0L)
                                .maxPublishedAgents(0L)
                                .maxReportAgentSessions(0L)
                                .maxUsers(0L)
                                .mfaEnabled(true)
                                .ssoEnabled(true)
                                .subscriptionCostUsd(0L)
                                .maxDirectories(0L)
                                .maxDirectoryFilesPerDirectory(0L)
                                .maxDirectoryIngestFiles(0L)
                                .maxDirectorySyncPlanActions(0L)
                                .addSpendingSoftAlertsUsdCent(0L)
                                .build()
                        )
                        .metronomePlanType(ProjectGetUsageResponse.Plan.MetronomePlanType.CONTRACT)
                        .metronomeRateCardAlias("metronome_rate_card_alias")
                        .name(ProjectGetUsageResponse.Plan.Name.ENTERPRISE)
                        .planFrequency(ProjectGetUsageResponse.Plan.PlanFrequency.ANNUAL)
                        .id("id")
                        .currentBillingPeriod(
                            ProjectGetUsageResponse.Plan.CurrentBillingPeriod.builder()
                                .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .failureCount(0L)
                        .isPaymentFailed(true)
                        .metronomeCustomerId("metronome_customer_id")
                        .addRecurringCredit(
                            ProjectGetUsageResponse.Plan.RecurringCredit.builder()
                                .creditAmount(0L)
                                .creditType(
                                    ProjectGetUsageResponse.Plan.RecurringCredit.CreditType
                                        .builder()
                                        .id("id")
                                        .name("name")
                                        .build()
                                )
                                .name("name")
                                .priority(0.0)
                                .productId("product_id")
                                .rolloverFraction(0.0)
                                .periodsDuration(0.0)
                                .build()
                        )
                        .startingOn(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .usage(
                    ProjectGetUsageResponse.Usage.builder()
                        .addActiveAlert(
                            ProjectGetUsageResponse.Usage.ActiveAlert
                                .CONFIGURED_SPEND_LIMIT_EXCEEDED
                        )
                        .addActiveFreeCreditsUsage(
                            ProjectGetUsageResponse.Usage.ActiveFreeCreditsUsage.builder()
                                .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .grantName("grant_name")
                                .remainingBalance(0L)
                                .startingBalance(0L)
                                .build()
                        )
                        .currentInvoiceTotalUsdCents(0L)
                        .totalExtractionAgents(0L)
                        .totalIndexedPages(0L)
                        .totalIndexes(0L)
                        .totalUsers(0L)
                        .build()
                )
                .build()

        assertThat(projectGetUsageResponse.plan())
            .isEqualTo(
                ProjectGetUsageResponse.Plan.builder()
                    .limits(
                        ProjectGetUsageResponse.Plan.Limits.builder()
                            .allowPayAsYouGo(true)
                            .maxConcurrentIndexJobs(0L)
                            .maxConcurrentParseJobsOther(0L)
                            .maxConcurrentParseJobsPremium(0L)
                            .maxDataSinks(0L)
                            .maxDataSources(0L)
                            .maxEmbeddingModels(0L)
                            .maxExtractionAgents(0L)
                            .maxExtractionJobs(0L)
                            .maxExtractionRuns(0L)
                            .maxFilesPerIndex(0L)
                            .maxIndexes(0L)
                            .maxMonthlyInvoiceTotalUsd(0L)
                            .maxOrganizations(0L)
                            .maxPagesPerIndex(0L)
                            .maxProjects(0L)
                            .maxPublishedAgents(0L)
                            .maxReportAgentSessions(0L)
                            .maxUsers(0L)
                            .mfaEnabled(true)
                            .ssoEnabled(true)
                            .subscriptionCostUsd(0L)
                            .maxDirectories(0L)
                            .maxDirectoryFilesPerDirectory(0L)
                            .maxDirectoryIngestFiles(0L)
                            .maxDirectorySyncPlanActions(0L)
                            .addSpendingSoftAlertsUsdCent(0L)
                            .build()
                    )
                    .metronomePlanType(ProjectGetUsageResponse.Plan.MetronomePlanType.CONTRACT)
                    .metronomeRateCardAlias("metronome_rate_card_alias")
                    .name(ProjectGetUsageResponse.Plan.Name.ENTERPRISE)
                    .planFrequency(ProjectGetUsageResponse.Plan.PlanFrequency.ANNUAL)
                    .id("id")
                    .currentBillingPeriod(
                        ProjectGetUsageResponse.Plan.CurrentBillingPeriod.builder()
                            .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .failureCount(0L)
                    .isPaymentFailed(true)
                    .metronomeCustomerId("metronome_customer_id")
                    .addRecurringCredit(
                        ProjectGetUsageResponse.Plan.RecurringCredit.builder()
                            .creditAmount(0L)
                            .creditType(
                                ProjectGetUsageResponse.Plan.RecurringCredit.CreditType.builder()
                                    .id("id")
                                    .name("name")
                                    .build()
                            )
                            .name("name")
                            .priority(0.0)
                            .productId("product_id")
                            .rolloverFraction(0.0)
                            .periodsDuration(0.0)
                            .build()
                    )
                    .startingOn(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(projectGetUsageResponse.usage())
            .isEqualTo(
                ProjectGetUsageResponse.Usage.builder()
                    .addActiveAlert(
                        ProjectGetUsageResponse.Usage.ActiveAlert.CONFIGURED_SPEND_LIMIT_EXCEEDED
                    )
                    .addActiveFreeCreditsUsage(
                        ProjectGetUsageResponse.Usage.ActiveFreeCreditsUsage.builder()
                            .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .grantName("grant_name")
                            .remainingBalance(0L)
                            .startingBalance(0L)
                            .build()
                    )
                    .currentInvoiceTotalUsdCents(0L)
                    .totalExtractionAgents(0L)
                    .totalIndexedPages(0L)
                    .totalIndexes(0L)
                    .totalUsers(0L)
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val projectGetUsageResponse =
            ProjectGetUsageResponse.builder()
                .plan(
                    ProjectGetUsageResponse.Plan.builder()
                        .limits(
                            ProjectGetUsageResponse.Plan.Limits.builder()
                                .allowPayAsYouGo(true)
                                .maxConcurrentIndexJobs(0L)
                                .maxConcurrentParseJobsOther(0L)
                                .maxConcurrentParseJobsPremium(0L)
                                .maxDataSinks(0L)
                                .maxDataSources(0L)
                                .maxEmbeddingModels(0L)
                                .maxExtractionAgents(0L)
                                .maxExtractionJobs(0L)
                                .maxExtractionRuns(0L)
                                .maxFilesPerIndex(0L)
                                .maxIndexes(0L)
                                .maxMonthlyInvoiceTotalUsd(0L)
                                .maxOrganizations(0L)
                                .maxPagesPerIndex(0L)
                                .maxProjects(0L)
                                .maxPublishedAgents(0L)
                                .maxReportAgentSessions(0L)
                                .maxUsers(0L)
                                .mfaEnabled(true)
                                .ssoEnabled(true)
                                .subscriptionCostUsd(0L)
                                .maxDirectories(0L)
                                .maxDirectoryFilesPerDirectory(0L)
                                .maxDirectoryIngestFiles(0L)
                                .maxDirectorySyncPlanActions(0L)
                                .addSpendingSoftAlertsUsdCent(0L)
                                .build()
                        )
                        .metronomePlanType(ProjectGetUsageResponse.Plan.MetronomePlanType.CONTRACT)
                        .metronomeRateCardAlias("metronome_rate_card_alias")
                        .name(ProjectGetUsageResponse.Plan.Name.ENTERPRISE)
                        .planFrequency(ProjectGetUsageResponse.Plan.PlanFrequency.ANNUAL)
                        .id("id")
                        .currentBillingPeriod(
                            ProjectGetUsageResponse.Plan.CurrentBillingPeriod.builder()
                                .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .endingBefore(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .failureCount(0L)
                        .isPaymentFailed(true)
                        .metronomeCustomerId("metronome_customer_id")
                        .addRecurringCredit(
                            ProjectGetUsageResponse.Plan.RecurringCredit.builder()
                                .creditAmount(0L)
                                .creditType(
                                    ProjectGetUsageResponse.Plan.RecurringCredit.CreditType
                                        .builder()
                                        .id("id")
                                        .name("name")
                                        .build()
                                )
                                .name("name")
                                .priority(0.0)
                                .productId("product_id")
                                .rolloverFraction(0.0)
                                .periodsDuration(0.0)
                                .build()
                        )
                        .startingOn(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .usage(
                    ProjectGetUsageResponse.Usage.builder()
                        .addActiveAlert(
                            ProjectGetUsageResponse.Usage.ActiveAlert
                                .CONFIGURED_SPEND_LIMIT_EXCEEDED
                        )
                        .addActiveFreeCreditsUsage(
                            ProjectGetUsageResponse.Usage.ActiveFreeCreditsUsage.builder()
                                .expiresAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .grantName("grant_name")
                                .remainingBalance(0L)
                                .startingBalance(0L)
                                .build()
                        )
                        .currentInvoiceTotalUsdCents(0L)
                        .totalExtractionAgents(0L)
                        .totalIndexedPages(0L)
                        .totalIndexes(0L)
                        .totalUsers(0L)
                        .build()
                )
                .build()

        val roundtrippedProjectGetUsageResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(projectGetUsageResponse),
                jacksonTypeRef<ProjectGetUsageResponse>(),
            )

        assertThat(roundtrippedProjectGetUsageResponse).isEqualTo(projectGetUsageResponse)
    }
}
